### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Mike-Dai** [Mike-Dai/HduHelper-Homepage#1]
- [ ] Replace the background image with white background.(icon)

- [ ] Change the font.

- [x] Use respective icons for services.

- [x] Remove contact form.

- [ ] Add links related to the club.

- [x] Add more items in timeline.

- [ ] Change the logo of departments.

 - [ ] ~~Split homepage into two pages.~~

- [x] Add toggle button to show/hide team and timeline sections.
